#!/usr/bin/env python
"""Generate schema.dbml and the README ER diagram from arbiter/schema.py.

Both artifacts are derived, never hand-written, so they cannot drift from the
loader. Everything structural - tables, columns, keys, id bands, relationship
endpoints and cardinality - comes from `arbiter.schema`. Edge counts, when
shown, come from `results/ontology.json`, which is a dump of the live
`/api/ontology` endpoint; without that file the diagrams render structure only
rather than inventing numbers.

    python scripts/gen_dbml.py            # writes schema.dbml, updates README
    python scripts/gen_dbml.py --check    # exit 1 if either is out of date
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from arbiter import schema as sch  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
DBML = ROOT / "schema.dbml"
README = ROOT / "README.md"
COUNTS = ROOT / "results" / "ontology.json"

BEGIN = "<!-- BEGIN GENERATED ERD -->"
END = "<!-- END GENERATED ERD -->"


def counts() -> dict:
    """Measured edge counts, if a dump of /api/ontology is present."""
    if not COUNTS.exists():
        return {}
    return json.loads(COUNTS.read_text(encoding="utf-8")).get("edges", {})


def band_note(entity: str) -> str:
    b = sch.ENTITIES[entity]["band"]
    if b is None:
        others = [k for k in sch.ARTIFACT_KINDS if k != "document"]
        return "id bands " + ", ".join(f"{sch.BASE[k]:,}+ ({k})" for k in others)
    return f"id band {sch.BASE[b]:,} .. {sch.BASE[b] + sch.SPAN - 1:,}"


def gen_dbml() -> str:
    n = counts()
    out = [
        "// Arbiter graph schema - GENERATED by scripts/gen_dbml.py.",
        "// Do not edit by hand; edit arbiter/schema.py and regenerate.",
        "//",
        "// Entity type is encoded in the integer id band, not in a label or a",
        "// column. HydraDB v0.1.0 accepts exactly one batch write form:",
        "//",
        "//   UNWIND $rows AS row CREATE (a {id: row.a})-[:REL]->(b {id: row.b})",
        "//",
        "// which carries ids only - no labels, no node properties, no edge",
        "// properties. So a node cannot be tagged with its type at insert time.",
        "// Instead each entity class owns a disjoint 1,000,000-wide id range and",
        "// a node's type is recoverable from its id alone, with no property",
        "// lookup. That also makes a typed-edge constraint (AUTHORED must point",
        "// at a document) an integer range check the engine answers from the id.",
        "//",
        "// Paste into https://dbdiagram.io/d to render.",
        "",
    ]

    for name, spec in sch.ENTITIES.items():
        out.append(f"Table {name} {{")
        for col, typ, key, note in spec["columns"]:
            attrs = []
            if key == "pk":
                attrs.append("pk")
            if note:
                attrs.append(f'note: "{note}"')
            # FK-ness is carried by the Ref lines below plus the note prefix
            suffix = " [" + ", ".join(attrs) + "]" if attrs else ""
            out.append(f"  {col} {typ}{suffix}")
        out.append(f'  Note: "{band_note(name)}"')
        out.append("}")
        out.append("")

    out.append("// -- Relationships. One Ref per edge type in the ontology. --")
    out.append("")
    for rel in sch.EDGE_TYPES:
        src, dst, card = sch.EDGE_ENDPOINTS[rel]
        op = sch.DBML_OP[card]
        tail = f" // {rel} - {card}"
        if rel in sch.UNPOPULATED:
            tail += "; declared but never emitted by build.py (0 edges)"
        elif rel in n:
            tail += f", {n[rel]:,} edges"
        # every edge leaves from its declared column; self-relationships use a
        # dedicated one because DBML cannot Ref a table to itself on one column
        col = sch.EDGE_SOURCE_COLUMN.get(rel, "id")
        if src == dst:
            tail += " (self-relationship)"
        out.append(f"Ref: {src}.{col} {op} {dst}.id{tail}")
    out.append("")
    return "\n".join(out)


def gen_mermaid() -> str:
    n = counts()
    out = ["```mermaid", "erDiagram"]
    for name, spec in sch.ENTITIES.items():
        out.append(f"    {name.upper()} {{")
        for col, typ, key, _note in spec["columns"]:
            k = " PK" if key == "pk" else (" FK" if key == "fk" else "")
            out.append(f"        {typ} {col}{k}")
        out.append("    }")
    for rel in sch.EDGE_TYPES:
        src, dst, card = sch.EDGE_ENDPOINTS[rel]
        op = sch.MERMAID_OP[card]
        if rel in sch.UNPOPULATED:
            label = f"{rel} declared only"
        elif rel in n:
            label = f"{rel} {n[rel]:,}"
        else:
            label = rel
        out.append(f'    {src.upper()} {op} {dst.upper()} : "{label}"')
    out.append("```")
    return "\n".join(out)


def splice_readme(text: str, block: str) -> str:
    if BEGIN not in text or END not in text:
        raise SystemExit("README markers missing; add them once by hand")
    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    return f"{head}{BEGIN}\n{block}\n{END}{tail}"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if generated artifacts are stale")
    args = ap.parse_args()

    dbml, mermaid = gen_dbml(), gen_mermaid()
    readme = splice_readme(README.read_text(encoding="utf-8"), mermaid)

    if args.check:
        stale = []
        if not DBML.exists() or DBML.read_text(encoding="utf-8") != dbml:
            stale.append("schema.dbml")
        if README.read_text(encoding="utf-8") != readme:
            stale.append("README.md ER diagram")
        if stale:
            print("STALE: " + ", ".join(stale) + " - run scripts/gen_dbml.py")
            return 1
        print("up to date: schema.dbml, README.md ER diagram")
        return 0

    DBML.write_text(dbml, encoding="utf-8")
    README.write_text(readme, encoding="utf-8")
    src = "with counts from results/ontology.json" if counts() else "structure only (no results/ontology.json)"
    print(f"wrote schema.dbml ({len(sch.ENTITIES)} tables, "
          f"{len(sch.EDGE_TYPES)} refs) and README ER diagram - {src}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
